# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .RISETransactionCommon import RISETransactionCommon

if __debug__:
    try:
        from typing import List
    except ImportError:
        List = None  # type: ignore


class RISESignTx(p.MessageType):
    MESSAGE_WIRE_TYPE = 125

    def __init__(
        self,
        address_n: List[int] = None,
        transaction: RISETransactionCommon = None,
    ) -> None:
        self.address_n = address_n if address_n is not None else []
        self.transaction = transaction

    @classmethod
    def get_fields(cls):
        return {
            1: ('address_n', p.UVarintType, p.FLAG_REPEATED),
            2: ('transaction', RISETransactionCommon, 0),
        }
