# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .RISEDelegateType import RISEDelegateType
from .RISEMultisignatureType import RISEMultisignatureType
from .RISESignatureType import RISESignatureType

if __debug__:
    try:
        from typing import List
    except ImportError:
        List = None  # type: ignore


class RISETransactionAsset(p.MessageType):

    def __init__(
        self,
        signature: RISESignatureType = None,
        delegate: RISEDelegateType = None,
        votes: List[str] = None,
        multisignature: RISEMultisignatureType = None,
    ) -> None:
        self.signature = signature
        self.delegate = delegate
        self.votes = votes if votes is not None else []
        self.multisignature = multisignature

    @classmethod
    def get_fields(cls):
        return {
            1: ('signature', RISESignatureType, 0),
            2: ('delegate', RISEDelegateType, 0),
            3: ('votes', p.UnicodeType, p.FLAG_REPEATED),
            4: ('multisignature', RISEMultisignatureType, 0),
        }
